insert into test_user (name, role) values ('Melisandra Elletson', 'Administrative Officer');
insert into test_user (name, role) values ('Adriana Diwell', 'Senior Cost Accountant');
insert into test_user (name, role) values ('Charo Joannic', 'Structural Analysis Engineer');
insert into test_user (name, role) values ('Tamera Remnant', 'Account Representative III');
insert into test_user (name, role) values ('Elsey Yabsley', 'Legal Assistant');
insert into test_user (name, role) values ('Charo Jarratt', 'Business Systems Development Analyst');
insert into test_user (name, role) values ('Carmelina Jullian', 'Administrative Assistant I');
insert into test_user (name, role) values ('Quent Enoksson', 'Internal Auditor');
insert into test_user (name, role) values ('Brigitte Brinkworth', 'Paralegal');
insert into test_user (name, role) values ('Cyrille Seman', 'Chemical Engineer');
insert into test_user (name, role) values ('Hayyim Leiden', 'Sales Associate');
insert into test_user (name, role) values ('Annice Wozencraft', 'Budget/Accounting Analyst IV');
insert into test_user (name, role) values ('Marijo Greenwood', 'Administrative Officer');
insert into test_user (name, role) values ('Agneta Thrower', 'Business Systems Development Analyst');
insert into test_user (name, role) values ('Skipp Riddett', 'Senior Quality Engineer');
insert into test_user (name, role) values ('Cherish Fiveash', 'Financial Advisor');
insert into test_user (name, role) values ('Merilee Bruhnsen', 'Assistant Manager');
insert into test_user (name, role) values ('Derry O''Carran', 'Paralegal');
insert into test_user (name, role) values ('Linn Barnaclough', 'Paralegal');
insert into test_user (name, role) values ('Vonni Scattergood', 'Project Manager');
