# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false

        main:
            pattern: ^/api/user
#            pattern: ~
            http_basic: ~
            provider: db_provider

            logout:
                path: /logout
#                target: /
#
#    access_control:
#            # require ROLE_ADMIN for /admin*
#            - { path: ^/admin, roles: ROLE_ADMIN }
    access_control:
#        - { path: ^/api/user, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }
#        - { path: ^/user/, role: ROLE_ADMIN }
#        - { path: ^/, role: ROLE_ADMIN }

    encoders:
        AppBundle\Entity\User:
#            algorithm: bcrypt
            algorithm: plaintext
